### ISSUE TITLE
Refactor Email Subscribe code

### ISSUE THREAD

**Issue by shankar2105** [maidsafe/safenetwork.tech#184]
Refactor email subscribe code to have proper state management, naming convention and other issue mentioned [here](https://github.com/maidsafe/safenetwork.tech/pull/177#discussion_r255614890)

**Comment by S-Coyle** [comment]
Has already been merged so closing.
Not clear if this went or should have went through QA before merge @calumcraig @shankar2105 ?

Will leave in QA column until clarified.

**Comment by S-Coyle** [comment]
As this code refactor has been merged to dev rather than master, I'm testing via our netlify deployment. This means that the email address subscription will not work - the request origin won't be authenticated, so a 403 forbidden will be received. Since this is a relatively low risk update I'll test by comparing the request sent from the current known working implementation (master), with the request sent from the latest dev branch, which will include these changes.

master:
`fetch("https://services.maidsafe.net/mail-subscription/api/1.0/subscribe", {"credentials":"omit","headers":{"content-type":"application/json"},"referrer":"https://deploy-preview-379--keen-stonebraker-bb1a10.netlify.com/","referrerPolicy":"no-referrer-when-downgrade","body":"{\"email\":\"zajoxinev@clickmail.info\"}","method":"POST","mode":"cors"});`

dev:
`fetch("https://services.maidsafe.net/mail-subscription/api/1.0/subscribe", {"credentials":"omit","headers":{"content-type":"application/json"},"referrer":"https://safenetwork.tech/","referrerPolicy":"no-referrer-when-downgrade","body":"{\"email\":\"zajoxinev@clickmail.info\"}","method":"POST","mode":"cors"});`

Verified that the only difference in the 2 requests is the origin URL, or as it's referred to above, the `referrer`.

QA approved
